### ISSUE TITLE
RN下B标签不能让文字加粗

### ISSUE THREAD

**Issue by YuanQuan** [ShaoGongBra/taro-html-view#1]
<b>加粗字体</b>

**Comment by ShaoGongBra** [comment]
样式里面是写了,其他端可以吗
```css
.html-b,
.html-strong {
  font-weight: bold;
}
```
